language: node_js
node_js:
  - "0.12"

cache:
  directories:
    - ./node_modules
    - ./bower_components
    - ./test/node_modules

install:
  - npm install
  - cd test && npm install && cd ..

script:
  - ./node_modules/grunt-cli/bin/grunt test
